name: CI/CD to DockerHub

on:
  push:
    branches:
      - master  # 혹은 사용 중인 브랜치

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      # 1. springboot 레포지토리를 별도 폴더로 체크아웃
      - name: Checkout Springboot Repo (Infra)
        uses: actions/checkout@v3
        with:
          repository: ljs3536/shoppingmall # 실제 레포 이름
          token: ${{ secrets.REPO_TOKEN }} # 생성한 PAT 사용 git setting의 secrets
          path: infra-repo # 다운로드 받을 폴더명
          
      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ljs3536/shoppingmall-flask:latest
            ljs3536/shoppingmall-flask:${{ github.sha }}

      - name: Update Flask YAML in Springboot Repo
        run: |
          # infra-repo 폴더 안에 있는 yaml 파일을 수정
          sed -i "s|image: ljs3536/shoppingmall-flask:.*|image: ljs3536/shoppingmall-flask:${{ github.sha }}|g" infra-repo/k8s/flask-deployment.yaml

      - name: Push Changes to Springboot Repo
        env:
          MY_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          cd infra-repo
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          # 토큰을 주소에 포함시켜 인증 에러 방지
          git remote set-url origin https://x-access-token:${MY_TOKEN}@github.com/ljs3536/shoppingmall.git
          
          git add k8s/flask-deployment.yaml
          git commit -m "Deploy: Update Flask image to ${{ github.sha }}"
          git push origin master
